_extends: kubewarden-policies:.github/release-drafter.yml
name-template: "environment-variable-policy/v$RESOLVED_VERSION"
tag-template: "environment-variable-policy/v$RESOLVED_VERSION"
tag-prefix: environment-variable-policy/v
include-paths:
  - "policies/environment-variable-policy/"
