_extends: kubewarden-policies:.github/release-drafter.yml
name-template: "ingress-policy/v$RESOLVED_VERSION"
tag-template: "ingress-policy/v$RESOLVED_VERSION"
tag-prefix: ingress-policy/v
include-paths:
  - "policies/ingress-policy/"
