[package]
name = "image-cve-policy"
version = "0.1.0"
authors = ["Flavio Castelli <fcastelli@suse.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
k8s-openapi = { version = "0.24.0", default-features = false, features = [
  "schemars",
  "latest",
] }
k8s-openapi-derive = "0.24.0"
kubewarden-policy-sdk = "0.12.0"
lazy_static = "1.5"
oci-spec = "0.7.1"
schemars = { version = "0.8", features = ["impl_json_schema"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
slog = "2.7"
thiserror = "2.0"

#[dev-dependencies]
anyhow = "1.0"
mockall = "0.13"
rstest = "0.24"
serde_yaml = "0.9"
serial_test = "3.2"
